#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p output

export TEXINPUTS=./examples:./output:
max_print_line=200 xelatex -output-driver="xdvipdfmx -z 0" -output-directory output examples/igrmk.tex
max_print_line=200 xelatex -output-driver="xdvipdfmx -z 0" -output-directory output examples/igrmk-cpp.tex
pdftoppm -singlefile -png -r 300 output/igrmk.pdf output/igrmk
