#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -lt 1 ]]; then
    echo "Usage: $0 <scope: full|all> [prefix]"
    exit 1
fi

scope="$1"
prefix="${2:-}"

case "$scope" in
  all|full|net|hft|python)
    ;;
  *)
    echo "Error: scope must be one of 'all', 'full', 'net', 'hft', or 'python'"
    exit 1
    ;;
esac

cd "$(dirname "$0")"
mkdir -p output

build_file() {
	tectonic -Z search-path=. -o output "examples/$1.tex"
	prefixed_name="$1"
	if [[ -n "$prefix" ]]; then
		prefixed_name="$prefix-$1"
		mv "output/$1.pdf" "output/$prefixed_name.pdf"
	fi
	pdftoppm -singlefile -png -r 300 "output/$prefixed_name.pdf" "output/$prefixed_name"
}

if [[ "$scope" == "full" || "$scope" == "all" ]]; then
	build_file igrmk-full
fi

if [[ "$scope" == "net" || "$scope" == "all" ]]; then
	build_file igrmk-net
fi

if [[ "$scope" == "hft" || "$scope" == "all" ]]; then
	build_file igrmk-hft
fi

if [[ "$scope" == "python" || "$scope" == "all" ]]; then
	build_file igrmk-python
fi
