---
name: Build CV

'on': {push: {tags: ['v*']}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y fonts-inter fonts-font-awesome poppler-utils texlive-xetex texlive-fonts-extra

      - name: Build artefacts
        run: ./build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          files: |
            igrmkcv.cls
            output/igrmk.pdf
            output/igrmk.png
